apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: kalm-benchmark
deploy:
  # dont wait for the resources to be ready
  # this settings seem to have no effect
  # keep it aroud nontheless if the bug is fixed at some point
  statusCheck: false
  # as fallback just wait for 10 seconds per file to override the default 10 minuntes
  statusCheckDeadlineSeconds: 10
  kubectl:
    manifests:
    # the files starting with '_' are prequisites for other resources
    - manifests/_*.yaml
    - manifests/cm-*.yaml
    - manifests/np-*.yaml
    - manifests/ns-*.yaml
    - manifests/pod-*.yaml
    - manifests/rbac-*.yaml
    - manifests/rel-*.yaml
    - manifests/res-*.yaml
    - manifests/sc-*.yaml
    - manifests/wl-*.yaml
    # deploy PSPs last so they have no effect on the misconfigured pods which are part of the benchmark
    - manifests/psp-*.yaml
